# Generated by Django 4.2.30 on 2026-05-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_customer_post_address_sizing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='preparing', max_length=20),
        ),
    ]
